steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '$_IMAGE_REPO', '.' ]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['beta', 'compute', 'instances', 'update-container', '$_INSTANCE', '--zone', '$_ZONE']

images: ['$_IMAGE_REPO']
